[package]
name = "kingdom-client"
version = "0.0.0"
authors = ["Michael Dorst <m@mdorst.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
